### ISSUE TITLE
After Swift 3 migration issue

### ISSUE THREAD

**Issue by AntonNix** [hryk224/InfiniteCollectionView#14]
Sorry if I do not leave many details. Feel free to send me a message.

After migration on 3 Swift next issues occurred:

I couldn't override methods of subclass InfiniteCollectionView and have next text of error:

"overriding non-open instance method outside of its defining module"
I will attach a screenshot.

XCode 8.3.2 (8E2002)
MacOS 10.12.3 (16D32)
InfiniteCollectionView (1.3.1)
SPEC CHECKSUMS: 
InfiniteCollectionView: 7f6a02482689c7aa34f87bc555b6daa94cb10f7a
![screen shot 2017-05-26 at 3 23 24 pm](https://cloud.githubusercontent.com/assets/24528570/26494579/f0fb5a20-4227-11e7-81e1-2d959b1eb6f7.png)

I fixed it by adding source code to my project, but it's not the best solution.

**Comment by hryk224** [comment]
Hi @AntonNix .

Sorry. That method can not be used.

`collectionView (_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int` 

Please use this.

```
func number(ofItems collectionView: UICollectionView) -> Int 
```

**Comment by AntonNix** [comment]
Thank you.
