### ISSUE TITLE
Why UIScrollViewDelegate not getting called

### ISSUE THREAD

**Issue by Cipherdale** [hryk224/InfiniteCollectionView#16]
i need to implement timer so it will scroll it self like featured page in app store, but when i call some delegate like this:

func scrollViewWillBeginDragging(_ scrollView: UIScrollView)
func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool)

none of them get called. please fix this... i love this library

**Comment by Cipherdale** [comment]
Ahhhh no problem i fix that already... i love this framework:)

**Comment by caroltam** [comment]
Hello, I am facing the same problem. How do you fix it?
